apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ddns-route53.fullname" . }}
  labels:
{{ include "ddns-route53.labels" . | indent 4 }}
data:
  access_key_id: {{ .Values.awsAccessKeyId | b64enc | quote }}
  secret_access_key: {{ .Values.awsSecretAccessKey | b64enc | quote }}
